In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from pymatgen.core.operations import SymmOp

In [2]:
mp_key = "kPLAfUWZpfzd6GRd9caSEcAaWKf3DxYL"
mp_id = "mp-569677"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
# Symétrie 1

In [5]:
i_atom = 5
i_symmop = 6

In [6]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [7]:
view.script('select strontium; color silver')
view.script('select iodine; color purple')
view.script('select nitrogen; color lightskyblue')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [8]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [9]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.33333333 0.66666667 0.8899473 ]


In [10]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.33333333  0.33333333 -0.8899473 ]


In [11]:
# Symétrie 2

In [12]:
i_atom = 3
i_symmop = 2

In [13]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [14]:
view.script('select strontium; color silver')
view.script('select iodine; color purple')
view.script('select nitrogen; color lightskyblue')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [15]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [16]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.66666667 0.33333333 0.55661396]


In [17]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.66666667 -0.33333333 -0.55661396]


In [18]:
# Symétrie 3 

In [19]:
i_atom = 9
i_symmop = 8

In [20]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [21]:
view.script('select strontium; color silver')
view.script('select iodine; color purple')
view.script('select nitrogen; color lightskyblue')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [22]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


In [23]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.33333333 0.66666667 0.66666667]


In [24]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.66666667 -0.33333333  0.66666667]
